insert into students (id, firstname, lastname, email, course_id) values (1, 'Philomena', 'Marcos', 'pmarcos0@ox.ac.uk', 1);
insert into students (id, firstname, lastname, email, course_id) values (2, 'Herschel', 'Shelborne', 'hshelborne1@so-net.ne.jp', 2);
insert into students (id, firstname, lastname, email, course_id) values (3, 'Gerek', 'Du Hamel', 'gduhamel2@bing.com', 3);
insert into students (id, firstname, lastname, email, course_id) values (4, 'Dar', 'Ruckhard', 'druckhard3@soup.io', 4);
insert into students (id, firstname, lastname, email, course_id) values (5, 'Archy', 'Dufore', 'adufore4@lulu.com', 5);
insert into students (id, firstname, lastname, email, course_id) values (6, 'Lucio', 'Hearson', 'lhearson5@sitemeter.com', 5);
insert into students (id, firstname, lastname, email, course_id) values (7, 'Nev', 'Sazio', 'nsazio6@ebay.co.uk', 4);
insert into students (id, firstname, lastname, email, course_id) values (8, 'Doro', 'Sells', 'dsells7@gov.uk', 3);
insert into students (id, firstname, lastname, email, course_id) values (9, 'Sammie', 'Pedden', 'spedden8@cbc.ca', 2);
insert into students (id, firstname, lastname, email, course_id) values (10, 'Pepe', 'Wannop', 'pwannop9@reuters.com', 1);